<?php
/**
 * Interface UserTokenAuthenticator
 *
 * The user token authenticator is responsible of validating and destroying
 * the auth token as well as authenticate a user by auth-token.
 *
 * The auth-tokens are generated by the "/v2/ilias-app/auth-token" rest route.
 *
 * @author  Nicolas Schäfli <ns@studer-raimann.ch>
 */
interface UserTokenAuthenticator {

	/**
	 * Authenticates the user with the given token.
	 * The token will always be deleted, regardless of the authentication result.
	 *
	 * @param int    $userId The id of the user which should be logged in.
	 * @param string $token  The token which should be used to authenticate the user with the given id.
	 *
	 * @return void
	 */
	public function authenticate($userId, $token);
}